name: musicfox
description: A sample command-line application.
version: 1.0.0
homepage: https://danlanhai.gitee.io

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  mp3_player: ^0.2.0
  colorful_cmd: ^1.5.1
  console: ^3.1.0
  netease_music_request: ^1.0.4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
